#!/bin/bash
Set this to the FQDN or IP address of the Delphix Engine
export DE="172.16.31.131"
# set this to the Delphix admin user name
export DELPHIX_ADMIN="delphix_admin"
# set this to the password for the Delphix admin user
export DELPHIX_PASS="landshark"
# Please change version are per your Delphix Engine CLI, if different
export VERSION="1.9.3"
